project_id = "siadaff"

[functions.submit-entry]
verify_jwt = false

[functions.submit-sponsor-inquiry]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.create-earlybird-order]
verify_jwt = false

[functions.confirm-earlybird-payment]
verify_jwt = false
